# This rule is not used by the project clusterscan-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to scan.spectrocloud.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterscan-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-viewer-role
rules:
- apiGroups:
  - scan.spectrocloud.com
  resources:
  - clusterscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scan.spectrocloud.com
  resources:
  - clusterscans/status
  verbs:
  - get
